import crypto from "crypto";

// We use ENCRYPTION_KEY, or fallback to AUTH_SECRET to ensure we have a secret.
// Both should ideally be 32+ characters long.
const getSecretKey = () => {
  const secret = process.env.ENCRYPTION_KEY || process.env.AUTH_SECRET;
  if (!secret) throw new Error("ENCRYPTION_KEY or AUTH_SECRET is required");
  
  // Ensure the key is exactly 32 bytes for aes-256-gcm
  return crypto.createHash("sha256").update(secret).digest("base64").substring(0, 32);
};

const ALGORITHM = "aes-256-gcm";

/**
 * Encrypts a plain text string using AES-256-GCM.
 * Returns the format `iv:authTag:encryptedData`.
 */
export function encryptToken(text: string): string {
  const iv = crypto.randomBytes(16);
  const key = getSecretKey();
  
  const cipher = crypto.createCipheriv(ALGORITHM, Buffer.from(key), iv);
  
  let encrypted = cipher.update(text, "utf8", "hex");
  encrypted += cipher.final("hex");
  const authTag = cipher.getAuthTag().toString("hex");
  
  return `${iv.toString("hex")}:${authTag}:${encrypted}`;
}

/**
 * Decrypts a token generated by `encryptToken`.
 */
export function decryptToken(encryptedData: string): string {
  // If the token isn't in the expected format, it might be an unencrypted legacy token
  if (!encryptedData.includes(":")) {
    return encryptedData;
  }

  const [ivHex, authTagHex, encryptedText] = encryptedData.split(":");
  if (!ivHex || !authTagHex || !encryptedText) return encryptedData;

  const key = getSecretKey();
  const decipher = crypto.createDecipheriv(ALGORITHM, Buffer.from(key), Buffer.from(ivHex, "hex"));
  decipher.setAuthTag(Buffer.from(authTagHex, "hex"));
  
  let decrypted = decipher.update(encryptedText, "hex", "utf8");
  decrypted += decipher.final("utf8");
  
  return decrypted;
}
